name: Main Workflow

on:
  push:
    paths:
      - '!**'
      - 'Dockerfile'
      - '.github/workflows/*.yml'
      - 'docker-entrypoint-initdb.d/**'
    branches:
      - master
  pull_request:
    paths:
      - '!**'
      - 'Dockerfile'
      - '.github/workflows/*.yml'
      - 'docker-entrypoint-initdb.d/**'
    branches:
      - '**'
  schedule:
    - cron: "0 0 1 * *"

jobs:
  container-build:
    name: Container Image Build (${{ matrix.pgtap-version }}, ${{ matrix.pg-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pgtap-version: [ 1.1.0, 1.2.0 ]
        pg-version: [ 9.6, 9, 10, 11, 12, 13, 14 ]
    steps:
      - uses: actions/checkout@v2

      - name: Buildah Action
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: pgtap
          tags: latest ${{ matrix.pgtap-version }}-pg${{ matrix.pg-version }}
          containerfiles: |
            ./Dockerfile
          build-args: |
            PG_CONTAINER_VERSION=${{ matrix.pg-version }}
            PGTAP_VERSION=${{ matrix.pgtap-version }}

      - name: Test Image
        shell: bash
        working-directory: examples
        run: |
          docker-compose up --renew-anon-volumes --abort-on-container-exit tests

      - name: Push To quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ matrix.pgtap-version }}-pg${{ matrix.pg-version }}
          registry: quay.io/twyla-ai
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push To docker.pkg.github.com
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ matrix.pgtap-version }}-pg${{ matrix.pg-version }}
          registry: docker.pkg.github.com/${{ github.repository }}
          username: publisher
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push To quay.io (latest tag)
        if: ${{ github.ref == 'refs/heads/main' && matrix.pg-version == '14'  }}
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: latest
          registry: quay.io/twyla-ai
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push To docker.pkg.github.com (latest tag)
        if: ${{ github.ref == 'refs/heads/main' && matrix.pg-version == '14'  }}
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: latest
          registry: docker.pkg.github.com/${{ github.repository }}
          username: publisher
          password: ${{ secrets.GITHUB_TOKEN }}
