name: Main Workflow

on:
  push:
    paths:
      - '!**'
      - 'Dockerfile'
      - '.github/workflows/*.yml'
      - 'docker-entrypoint-initdb.d/**'
    branches:
      - main
  pull_request:
    paths:
      - '!**'
      - 'Dockerfile'
      - '.github/workflows/*.yml'
      - 'docker-entrypoint-initdb.d/**'
    branches:
      - '**'
  schedule:
    - cron: "0 0 1 * *"

jobs:
  container-build:
    name: Container Image Build (${{ matrix.pgtap-version }}, ${{ matrix.pg-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pgtap-version: [ 1.3.1 ]
        pg-version: [ 9, 10, 11, 12, 13, 14, 15, 16 ]
    steps:
      - uses: actions/checkout@v3

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: pgtap
          tags: latest ${{ matrix.pgtap-version }}-pg${{ matrix.pg-version }}
          containerfiles: |
            ./Dockerfile
          build-args: |
            PG_CONTAINER_VERSION=${{ matrix.pg-version }}
            PGTAP_VERSION=${{ matrix.pgtap-version }}

      - name: Test Image
        shell: bash
        working-directory: examples
        run: |
          pipx install podman-compose
          podman-compose up --renew-anon-volumes --abort-on-container-exit --exit-code-from tests tests
          podman-compose down

      - name: Push To quay.io
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ matrix.pgtap-version }}-pg${{ matrix.pg-version }}
          registry: quay.io/abn
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push To docker.pkg.github.com
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ matrix.pgtap-version }}-pg${{ matrix.pg-version }}
          registry: docker.pkg.github.com/${{ github.repository }}
          username: publisher
          password: ${{ secrets.GITHUB_TOKEN }}
